import { useEffect, useState } from 'react';
import { BookOpen, ExternalLink, LibraryBig, Loader2, Search } from 'lucide-react';
import { supabase } from '@/lib/supabase';

interface LibraryBook { id: string; title: string; author: string; description: string; cover_url: string; content_url: string; category: string; }

export function LibraryPage() {
  const [books, setBooks] = useState<LibraryBook[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  useEffect(() => { supabase.from('library_books').select('*').order('title').then(({ data }) => { setBooks(data ?? []); setLoading(false); }); }, []);
  const visible = books.filter((book) => `${book.title} ${book.author} ${book.category}`.toLowerCase().includes(search.toLowerCase()));
  return <main className="min-h-[calc(100vh-64px)] bg-[#fdfaf6]"><div className="max-w-6xl mx-auto px-4 sm:px-6 py-8 sm:py-12"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 mb-8"><div><p className="text-xs uppercase tracking-[0.2em] text-gold-600 font-medium mb-2">Leitura gratuita</p><h1 className="font-serif text-4xl sm:text-5xl text-primary-900">Biblioteca católica</h1><p className="text-secondary-600 mt-2">Livros para aprofundar sua vida espiritual e conhecer melhor a fé.</p></div><div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-secondary-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar livro" className="rounded-full border border-secondary-200 bg-white pl-9 pr-4 py-2.5 text-sm focus:outline-none focus:ring-2 focus:ring-primary-300" /></div></div>{loading ? <div className="flex justify-center py-16"><Loader2 size={20} className="animate-spin text-secondary-400" /></div> : <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{visible.map((book) => <article key={book.id} className="rounded-2xl border border-gold-200/60 bg-white p-6 hover:shadow-md transition-shadow"><div className="w-12 h-12 rounded-xl bg-primary-50 text-primary-700 flex items-center justify-center mb-4"><BookOpen size={22} /></div><p className="text-xs uppercase tracking-wider text-gold-600 font-medium">{book.category}</p><h2 className="font-serif text-2xl text-primary-900 mt-1">{book.title}</h2><p className="text-sm text-secondary-500 mt-1">{book.author}</p><p className="text-sm text-secondary-600 leading-relaxed mt-4">{book.description}</p>{book.content_url ? <a href={book.content_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-full bg-primary-700 text-white text-sm px-4 py-2 mt-5 hover:bg-primary-800"><BookOpen size={15} /> Ler agora</a> : <span className="inline-flex items-center gap-2 text-sm text-secondary-400 mt-5"><LibraryBig size={15} /> Conteúdo em breve</span>}</article>)}</div>}{!loading && visible.length === 0 && <div className="text-center py-16 text-secondary-500">Nenhum livro encontrado.</div>}<div className="mt-12 rounded-2xl bg-secondary-950 text-white p-7 flex flex-col sm:flex-row items-start sm:items-center gap-4"><LibraryBig className="text-gold-400 flex-shrink-0" size={28} /><div><h2 className="font-serif text-2xl">Uma biblioteca que cresce com você</h2><p className="text-sm text-secondary-300 mt-1">Estamos reunindo obras católicas disponíveis gratuitamente para todos.</p></div><ExternalLink className="hidden sm:block ml-auto text-secondary-400" size={20} /></div></div></main>;
}
